### ISSUE TITLE
Startup crash

### ISSUE THREAD

**Issue by teefssi** [SuperCoder7979/simplexterrain#42]
recently installed this mod for my server for my friends, it works really well for me but for some reason, a certain friend crashes when he starts up. here's the crash log: 
[message.txt](https://github.com/SuperCoder7979/simplexterrain/files/6422677/message.txt)

**Comment by MenacingPerson** [comment]
try installing fabric api?

**Comment by StefanJanssen95** [comment]
I don't think that's the issue, from the log file:
> fabric: Fabric API 0.33.1+1.16
> fabric-api-base: Fabric API Base 0.2.1+9354966b7d

It seems that the error was thrown [here](https://github.com/SuperCoder7979/simplexterrain/blob/a81d6d40317332e9cc7658ec7a114d7c805350fc/src/main/java/supercoder79/simplexterrain/client/GoVote.java#L44)
> 	at supercoder79.simplexterrain.client.GoVote.init(GoVote.java:44)

I remember it was fixed in one of the other plugins. A quick search gave me this commit as fix:
https://github.com/SuperCoder7979/fabric-chunkpregenerator/commit/00087f342602a58e80979b2911e0a62a7ba6b325


The reason it's crashing for the friend is because he is not using a Windows PC unfortunately.

**Comment by edenstrom** [comment]
This issue is still happening. Crashes on startup on macOS.

I see that a PR was created back in October for this issue (https://github.com/SuperCoder7979/simplexterrain/pull/31). Maybe it's possible to remove the GoVote file completely?

Can it be merged, or should a new PR be created? I can help if necessary.

Sorry for pinging you @SuperCoder7979, but this seems important for non-Windows users.
